language: c
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build && cmake .. && make && make check && make isolation_check && make contrib_check && make plperl_check && make plpython_check && make pltcl_check && make ecpg_check
